"use client";

import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-cream py-20 px-4">
      {/* Decorative Background Elements */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-0 left-0 w-72 h-72 bg-primary/10 rounded-full blur-3xl" />
        <div className="absolute bottom-0 right-0 w-96 h-96 bg-accent/10 rounded-full blur-3xl" />
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-4xl mx-auto"
      >
        <div className="glass p-8 rounded-2xl border border-white/20 backdrop-blur-xl">
          <h1 className="text-4xl font-bold mb-8 bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
            Terms and Conditions
          </h1>
          
          <div className="space-y-8 text-text">
            <section>
              <h2 className="text-2xl font-semibold mb-3 text-primary">Acceptance of Terms</h2>
              <p className="text-lg">By using our services, you accept the conditions described in this document.</p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold mb-3 text-primary">Services Offered</h2>
              <p className="text-lg">
                Maikua provides web development and AI research services. 
                We reserve the right to modify or discontinue services as necessary.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold mb-3 text-primary">Intellectual Property</h2>
              <p className="text-lg">
                All content generated by Maikua is protected by copyright and cannot 
                be reproduced without authorization.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold mb-3 text-primary">Liability</h2>
              <p className="text-lg">
                We do not guarantee specific results and are not responsible for losses 
                arising from the use of our services.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold mb-3 text-primary">Jurisdiction</h2>
              <p className="text-lg">These conditions are governed by the laws of the United States.</p>
            </section>
          </div>

          <Link 
            href="/"
            className="inline-flex items-center mt-8 px-6 py-3 text-white bg-primary rounded-lg hover:bg-accent transition-colors duration-300"
          >
            <ArrowLeft className="mr-2 h-5 w-5" />
            Back to home
          </Link>
        </div>
      </motion.div>
    </div>
  );
}